# Generated by Django 3.2 on 2022-11-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addr',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='addr',
            name='county',
            field=models.CharField(default='', max_length=20, verbose_name='区县'),
        ),
    ]
