# Generated by Django 3.2 on 2022-11-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221104_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='address',
            field=models.CharField(max_length=200, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='addr',
            name='county',
            field=models.CharField(max_length=20, verbose_name='区县'),
        ),
    ]
