# Generated by Django 3.2 on 2022-11-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221108_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addr',
            options={'verbose_name': '收货地址表', 'verbose_name_plural': '收货地址表'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '地区表', 'verbose_name_plural': '地区表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='verifcode',
            options={'verbose_name': '手机验证码表', 'verbose_name_plural': '手机验证码表'},
        ),
        migrations.AlterField(
            model_name='area',
            name='pid',
            field=models.IntegerField(verbose_name='上级id'),
        ),
    ]
