# Generated by Django 3.2 on 2022-11-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20221108_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsgroup',
            options={'verbose_name': '商品分类表', 'verbose_name_plural': '商品分类表'},
        ),
    ]
