# Generated by Django 3.2 on 2022-11-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goodsgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.CharField(help_text='商品描述', max_length=20, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(default='', help_text='标题', max_length=10, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='goodsgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='分类图标'),
        ),
    ]
